### ISSUE TITLE
Disable the qt5-git packages once Arch is updated

### ISSUE THREAD

**Issue by iBelieve** [papyros/repository#1]
Qt 5.5 is out, so we only need to ship our patched version of QtWayland.

We're still waiting for Arch to update the Qt 5 packages: https://www.archlinux.org/packages/extra/x86_64/qt5-base/

**Comment by VirusKA** [comment]
so after that, disk images will be released?

**Comment by brunelli** [comment]
@iBeliever Qt 5.5 is already in `extra` :smiley:

**Comment by iBelieve** [comment]
@ianbrunelli Nice. I updated the PKGBUILDs to point the Arch Qt 5.5 packages, and now am working on resolving build issues. We should have new packages soon!

**Comment by IdrissDimson** [comment]
\o/

**Comment by iBelieve** [comment]
This has been implemented for a long time. We still ship a few modified packages with patches though.
